/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Nat64,
  'createdAt' : IDL.Int,
  'completed' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DaySummary = IDL.Record({
  'total' : IDL.Nat,
  'date' : IDL.Text,
  'completed' : IDL.Nat,
});
export const StreakInfo = IDL.Record({
  'longestStreak' : IDL.Nat,
  'currentStreak' : IDL.Nat,
  'milestones' : IDL.Vec(IDL.Nat),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTask' : IDL.Func([IDL.Text, IDL.Nat64], [Task], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMonthHistory' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(DaySummary)],
      ['query'],
    ),
  'getStreakInfo' : IDL.Func([], [StreakInfo], ['query']),
  'getTasksByDate' : IDL.Func([IDL.Nat64], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleTask' : IDL.Func([IDL.Nat], [], []),
  'updateTask' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Nat64,
    'createdAt' : IDL.Int,
    'completed' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DaySummary = IDL.Record({
    'total' : IDL.Nat,
    'date' : IDL.Text,
    'completed' : IDL.Nat,
  });
  const StreakInfo = IDL.Record({
    'longestStreak' : IDL.Nat,
    'currentStreak' : IDL.Nat,
    'milestones' : IDL.Vec(IDL.Nat),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTask' : IDL.Func([IDL.Text, IDL.Nat64], [Task], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMonthHistory' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(DaySummary)],
        ['query'],
      ),
    'getStreakInfo' : IDL.Func([], [StreakInfo], ['query']),
    'getTasksByDate' : IDL.Func([IDL.Nat64], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleTask' : IDL.Func([IDL.Nat], [], []),
    'updateTask' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };